[env:edvin-alka]
extends = esp32_base
board = esp32dev
build_flags =
  ${esp32_base.build_flags}
  -I variants/esp32/edvin-alka
  -D ARDUINO_ARCH_ESP32
  -D USE_SX1276
  -D USE_RF95
  -D RF95_IRQ=26
  -D RF95_RESET=14
  -D RF95_DIO1=33
  -D LORA_CS=18
  -D LORA_SCK=5
  -D LORA_MISO=19
  -D LORA_MOSI=27
  -D RESET_OLED=16
  -D VEXT_ENABLE=21
  -D I2C_SDA=4
  -D I2C_SCL=15
  -D BUTTON_PIN=0
  -D BATTERY_PIN=35
  -D USE_SSD1306
  -D RADIOLIB_EXCLUDE_SX127X=0
